name: Publish Package

on:
  push:
    tags:
      - v*

permissions:
  contents: write
  id-token: write

jobs:
  release:
    runs-on: ubuntu-latest
    environment: Release

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: pnpm/action-setup@v3

      - name: Use Node.js 20
        uses: actions/setup-node@v3
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org/
          cache: pnpm

      - run: pnpm install --frozen-lockfile --prefer-offline

      - uses: actions/github-script@v7
        id: checkPrerelease
        name: Check if prerelease
        with:
          script: |
            const version = context.ref.replace('refs/tags/v', '').split('.');
            core.setOutput('preRelease', String(version[1] % 2 !== 0))

      - name: Publish to Visual Studio Marketplace
        id: publishToVSMarketplace
        uses: HaaLeo/publish-vscode-extension@v1
        with:
          preRelease: ${{ steps.checkPrerelease.outputs.preRelease == 'true' }}
          pat: ${{ secrets.VS_MARKETPLACE_TOKEN }}
          registryUrl: https://marketplace.visualstudio.com
          dependencies: false

      - name: Publish to Open VSX Registry
        uses: HaaLeo/publish-vscode-extension@v1
        with:
          extensionFile: ${{ steps.publishToVSMarketplace.outputs.vsixPath }}
          pat: ${{ secrets.OPEN_VSX_TOKEN }}

      - name: Generate Changelog
        if: steps.checkPrerelease.outputs.preRelease == 'false'
        run: npx changelogithub
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate Prerelease Changelog
        if: steps.checkPrerelease.outputs.preRelease == 'true'
        run: npx changelogithub --prerelease
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
